language: r
sudo: true
cache: packages
warnings_are_errors: false

# temporarily try to circumvent travis built-in bioc
# related: https://travis-ci.community/t/in-r-version-4-0-0-library-path-not-writable/9744/8

# r:
#  - bioc-devel
#  - bioc-release

r: release

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## use release or devel
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions


# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


r_packages:
  - covr
  - BiocManager

# r_github_packages:
#   - r-lib/covr

# bioc_required: true

# only report coverage for the release version
# after_success:
#   - test $TRAVIS_R_VERSION_STRING = 'bioc-release' && Rscript -e 'covr::codecov()'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
